[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"
  environment = { 
    SECRETS_SCAN_OMIT_KEYS = "REACT_APP_ENV,REACT_APP_API_URL,NODE_VERSION,NPM_VERSION",
    SECRETS_SCAN_OMIT_PATHS = "build/**,node_modules/**,.git/**,*.md,package.json,public/**"
  }

# Redirect per SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers per file statici
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Variabili d'ambiente per produzione
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"